version: '3'

services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    ports:
      - "80:80"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - dvwa_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - dvwa_network

networks:
  dvwa_network:
    driver: bridge

volumes:
  dvwa_data:
